[package]
org = "example"
name = "observability_demo"
version = "0.1.0"
distribution = "2201.13.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name = "sql"
version = "1.19.0"

[[dependency]]
org = "ballerinax"
name = "postgresql"
version = "1.18.0"

# PostgreSQL JDBC driver
[[platform.java21.dependency]]
groupId = "org.postgresql"
artifactId = "postgresql"
version = "42.7.4"
